---
- name: Configure etcd cluster
  hosts: servers 
  become: yes
  gather_facts: yes 
  tasks:
    - name: Install pgbackrest
      ansible.builtin.apt:
        name: pgbackrest
        update_cache: yes
        state: present 
      become: yes
    - name: Ensure /var/log/pgbackrest directory exists
      ansible.builtin.file:
        path: /var/log/pgbackrest
        state: directory
        mode: '0770'
        owner: postgres
        group: postgres
      become: yes
    - name: Ensure /var/log/pgbackrest directory exists
      ansible.builtin.file:
        path: /var/log/pgbackrest
        state: directory
        owner: postgres
        group: postgres
      become: yes
    - name: Ensure /etc/pgbackrest/ directory exists
      ansible.builtin.file:
        path: /etc/pgbackrest/
        state: directory
      become: yes
    - name: Ensure /data/certs directory exists for S3
      ansible.builtin.file:
        path: /data/certs
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'
      become: yes
    - name: Copy pgbackrest configuration template to /etc/pgbackrest/pgbackrest.conf
      ansible.builtin.template:
        src: pgbackrest_conf.j2
        dest: /etc/pgbackrest/pgbackrest.conf
        owner: postgres
        group: postgres
      become: yes
    - name: Copy ca.crt to nodes Patroni
      ansible.builtin.template:
        src: ca.j2
        dest: /data/certs/ca.crt
        owner: postgres
        group: postgres
        mode: '0600'
      become: yes
    - name: Copy server.crt to nodes Patroni
      ansible.builtin.template:
        src: server_crt.j2
        dest: /data/certs/server.crt
        owner: postgres
        group: postgres
        mode: '0600'
      become: yes
    - name: Copy server.key to nodes Patroni
      ansible.builtin.template:
        src: server_key.j2
        dest: /data/certs/server.key
        owner: postgres
        group: postgres
        mode: '0600'
      become: yes
